// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM3S6gp9Z-LN_7xp0-KSR0wprSVDklH8o',
    appId: '1:63442796503:web:fb7b4b25be471dcba75592',
    messagingSenderId: '63442796503',
    projectId: 'cbex-2be3a',
    authDomain: 'cbex-2be3a.firebaseapp.com',
    storageBucket: 'cbex-2be3a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPXAJ3pNNhhtj6hQqkeFNwM9vAau_8ZTw',
    appId: '1:63442796503:android:5a3ab6433cffa9cea75592',
    messagingSenderId: '63442796503',
    projectId: 'cbex-2be3a',
    storageBucket: 'cbex-2be3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM4PA-jtHSir3MSBPgseYH0iKewFO9_HI',
    appId: '1:63442796503:ios:7e989dc686988b2ba75592',
    messagingSenderId: '63442796503',
    projectId: 'cbex-2be3a',
    storageBucket: 'cbex-2be3a.firebasestorage.app',
    iosBundleId: 'com.cbm.cbex',
  );
}
